### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by pgonzal** [TypeForce/ts-doc-gen#49]
Is this project still being actively maintained?  Did it ever ship?  If so would it be possible to change the name to avoid confusion with the [@microsoft/tsdoc](https://www.npmjs.com/package/@microsoft/tsdoc) project?

@BurtHarris

**Comment by BurtHarris** [comment]
@samvv, I tend to agree with the logic expressed above, are you willing to somehow rename or delete this project?
